### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [localh0t/wildpwn#1]
Hello.

I want to add your tool into [ArchStrike](https://github.com/ArchStrike/ArchStrike/) but your tool doesn't have a license.

Is it possible for you to add in a license file?

**Comment by localh0t** [comment]
Done! Would love to see the tool in ArchStrike.

**Comment by xorond** [comment]
Thanks! I'll let you know from here when the tool is added in!

**Comment by xorond** [comment]
Added! See [here](https://archstrike.org/packages/wildpwn-git)
